---
- name: Reboot servers with specific users
  hosts: "{{ server_name }}"  # Use the variable passed for the server name
  #remote_user: "{{ ansible_user }}"  # This will use the username specified in the hosts file
  become: yes  # Don't use sudo or become root
  become_user: root
  tasks:
    - name: Reboot the server
      ansible.builtin.reboot:
        reboot_timeout: 60    # Timeout for rebooting
        test_command: whoami   # Command to test if the server is back online
      register: reboot_result
      until: reboot_result is success
      retries: 3
      delay: 10
